baseURL = "https://syntropic.xyz/"
languageCode = "en-us"
title = "syntropic.xyz"
copyright = "All rights reserved"

[params]
  description = "Thoughts on prediction, information compression and coherence"
  author = "Joshua Shane"

[menus]
  [[menus.main]]
    name = "Essays"
    url = "/posts/"
    weight = 1
  [[menus.main]]
    name = "Writing"
    url = "/writing/"
    weight = 2
  [[menus.main]]
    name = "Signals"
    url = "/intelligence/"
    weight = 3
  [[menus.main]]
    name = "Projects"
    url = "/projects/"
    weight = 4
  [[menus.main]]
    name = "Telos"
    url = "/telos/"
    weight = 5
  [[menus.main]]
    name = "About"
    url = "/about/"
    weight = 6

[markup]
  [markup.highlight]
    style = "monokai"
    lineNos = false
    codeFences = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputFormats.RSS]
  mediaType = "application/rss+xml"
  baseName = "feed"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]

[outputFormats.JSON]
  mediaType = "application/json"
  baseName = "index"
  isPlainText = true
