baseURL = "https://syntropic.xyz/"
languageCode = "en-us"
title = "The Syntropic Lens"
copyright = "All rights reserved"

[params]
  description = "Thoughts on prediction, information compression and coherence"
  # Uncomment and set your Plausible domain to enable analytics
  # plausibleDomain = "syntropic.xyz"

[markup]
  [markup.highlight]
    style = "monokai"
    lineNos = false
    codeFences = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputFormats.RSS]
  mediaType = "application/rss+xml"
  baseName = "feed"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]

[outputFormats.JSON]
  mediaType = "application/json"
  baseName = "index"
  isPlainText = true
